"""Phase 9 — PDF report generation via reportlab."""
import io
import logging
from datetime import datetime, timezone, timedelta
from collections import defaultdict
from typing import Optional

from fastapi import APIRouter, Request, Depends, Query, HTTPException
from fastapi.responses import StreamingResponse
from sqlalchemy import select

from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak,
)

from db import Transaction, Budget, MaaserLedger, SplitTransaction
from auth import get_current_user

logger = logging.getLogger("reports")

EMERALD = colors.HexColor("#10B981")
INK = colors.HexColor("#0B0F19")
MUTED = colors.HexColor("#6B7280")
SOFT = colors.HexColor("#F1F5F9")


def _styles():
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle("t", parent=base["Title"], fontName="Helvetica-Bold",
                                fontSize=26, leading=30, textColor=INK, spaceAfter=4),
        "sub": ParagraphStyle("s", parent=base["Normal"], fontName="Helvetica",
                              fontSize=10, leading=14, textColor=MUTED, spaceAfter=18),
        "h2": ParagraphStyle("h2", parent=base["Heading2"], fontName="Helvetica-Bold",
                             fontSize=14, leading=18, textColor=INK, spaceAfter=8, spaceBefore=14),
        "label": ParagraphStyle("l", parent=base["Normal"], fontName="Helvetica-Bold",
                                fontSize=8, leading=10, textColor=MUTED, spaceAfter=2),
        "kpi": ParagraphStyle("k", parent=base["Normal"], fontName="Helvetica-Bold",
                              fontSize=18, leading=22, textColor=INK),
        "body": ParagraphStyle("b", parent=base["Normal"], fontName="Helvetica",
                               fontSize=10, leading=14, textColor=INK),
        "muted": ParagraphStyle("m", parent=base["Normal"], fontName="Helvetica",
                                fontSize=9, leading=12, textColor=MUTED),
    }


def _header_footer(canvas, doc, user_email: str, kind: str):
    canvas.saveState()
    canvas.setFillColor(EMERALD)
    canvas.rect(0, A4[1] - 6, A4[0], 6, fill=1, stroke=0)
    canvas.setFont("Helvetica-Bold", 9)
    canvas.setFillColor(INK)
    canvas.drawString(15 * mm, A4[1] - 14 * mm, "FinanceAI")
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(MUTED)
    canvas.drawRightString(A4[0] - 15 * mm, A4[1] - 14 * mm, kind)
    canvas.setFont("Helvetica", 7)
    canvas.setFillColor(MUTED)
    canvas.drawString(15 * mm, 10 * mm,
                      f"Generated by FinanceAI · {user_email} · {datetime.now(timezone.utc).strftime('%d %b %Y %H:%M UTC')}")
    canvas.drawRightString(A4[0] - 15 * mm, 10 * mm, f"Page {doc.page}")
    canvas.restoreState()


def _kpi_table(s, items):
    cells = [[
        Paragraph(label, s["label"]), Paragraph(value, s["kpi"])
    ] for label, value in items]
    grouped = [cells[i:i + 4] for i in range(0, len(cells), 4)]
    table_data = []
    for g in grouped:
        rowA = []
        rowB = []
        for cell in g:
            rowA.append(cell[0])
            rowB.append(cell[1])
        while len(rowA) < 4:
            rowA.append("")
            rowB.append("")
        table_data.append(rowA)
        table_data.append(rowB)
    t = Table(table_data, colWidths=[42 * mm] * 4)
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), SOFT),
        ("BOX", (0, 0), (-1, -1), 0, colors.transparent),
        ("LEFTPADDING", (0, 0), (-1, -1), 10),
        ("RIGHTPADDING", (0, 0), (-1, -1), 10),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ("ROUNDEDCORNERS", [6, 6, 6, 6]),
    ]))
    return t


def _tx_table(s, txs, limit=None):
    rows = [["Date", "Description", "Category", "Amount"]]
    use = txs[:limit] if limit else txs
    for t in use:
        amt = t.get("amount", 0)
        rows.append([
            (t.get("date") or "")[:10],
            (t.get("description") or "")[:40],
            (t.get("category") or "").capitalize(),
            f"{'+' if amt > 0 else '−'}£{abs(amt):.2f}",
        ])
    tbl = Table(rows, colWidths=[24 * mm, 80 * mm, 30 * mm, 30 * mm])
    tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), INK),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 8),
        ("FONTSIZE", (0, 1), (-1, -1), 9),
        ("ALIGN", (-1, 1), (-1, -1), "RIGHT"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, SOFT]),
        ("LINEBELOW", (0, 0), (-1, -1), 0.25, colors.HexColor("#E5E7EB")),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    return tbl


def _cat_table(s, categories):
    rows = [["Category", "Spend"]]
    for c in categories[:8]:
        rows.append([c.get("name", "").capitalize(), f"£{c.get('value', 0):.2f}"])
    t = Table(rows, colWidths=[80 * mm, 30 * mm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), INK),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 8),
        ("FONTSIZE", (0, 1), (-1, -1), 9),
        ("ALIGN", (-1, 1), (-1, -1), "RIGHT"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, SOFT]),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    return t


async def _gather(session, user_id: str, month: Optional[str] = None, year: Optional[int] = None):
    base_q = select(Transaction).where(Transaction.user_id == user_id)
    if month:
        start = datetime.strptime(f"{month}-01", "%Y-%m-%d").replace(tzinfo=timezone.utc)
        if month[5:7] == "12":
            end = datetime(int(month[:4]) + 1, 1, 1, tzinfo=timezone.utc)
        else:
            end = datetime(int(month[:4]), int(month[5:7]) + 1, 1, tzinfo=timezone.utc)
        base_q = base_q.where(Transaction.date >= start, Transaction.date < end)
    elif year:
        start = datetime(year, 1, 1, tzinfo=timezone.utc)
        end = datetime(year + 1, 1, 1, tzinfo=timezone.utc)
        base_q = base_q.where(Transaction.date >= start, Transaction.date < end)

    result = await session.execute(base_q.order_by(Transaction.date.desc()).limit(5000))
    txs_raw = [
        t
        for t in result.scalars().all()
        if getattr(t, "approval_status", "approved") == "approved"
        and t.tx_type != "transfer"
        and not getattr(t, "transfer_pair_id", None)
    ]
    split_map = defaultdict(list)
    if txs_raw:
        split_result = await session.execute(
            select(SplitTransaction).where(
                SplitTransaction.user_id == user_id,
                SplitTransaction.parent_transaction_id.in_(
                    [t.transaction_id for t in txs_raw]
                ),
            )
        )
        for split in split_result.scalars().all():
            split_map[split.parent_transaction_id].append(split)

    txs = []
    income = 0.0
    spend = 0.0
    for t in txs_raw:
        splits = split_map.get(t.transaction_id) or []
        if splits:
            sign = 1 if float(t.amount or 0) >= 0 else -1
            entries = [
                {
                    "transaction_id": t.transaction_id,
                    "amount": abs(float(s.amount or 0)) * sign,
                    "currency": t.currency,
                    "description": s.description or t.description,
                    "merchant": t.merchant_name,
                    "category": s.category or t.category,
                    "date": t.date.isoformat() if t.date else "",
                }
                for s in splits
            ]
        else:
            entries = [
                {
                    "transaction_id": t.transaction_id,
                    "amount": t.amount,
                    "currency": t.currency,
                    "description": t.description,
                    "merchant": t.merchant_name,
                    "category": t.category,
                    "date": t.date.isoformat() if t.date else "",
                }
            ]
        for d in entries:
            txs.append(d)
            if d["amount"] > 0:
                income += d["amount"]
            else:
                spend += -d["amount"]

    balance = income - spend
    savings_rate = ((income - spend) / income * 100) if income > 0 else 0
    health_score = max(0, min(100, int(savings_rate * 2 + (50 if balance > 0 else 0))))

    cats = defaultdict(float)
    for t in txs:
        if t["amount"] < 0:
            cats[t.get("category", "uncategorized")] += -t["amount"]
    cat_list = [{"name": k, "value": v} for k, v in sorted(cats.items(), key=lambda x: -x[1])]

    budget_result = await session.execute(select(Budget).where(Budget.user_id == user_id))
    budgets_raw = budget_result.scalars().all()
    budgets = []
    for b in budgets_raw:
        spent = sum(-t["amount"] for t in txs if t["amount"] < 0 and t["category"] == b.category)
        budgets.append({
            "budget_id": b.budget_id,
            "category": b.category,
            "limit": b.amount,
            "spent": spent,
        })

    tz_result = await session.execute(
        select(MaaserLedger).where(MaaserLedger.user_id == user_id)
        .order_by(MaaserLedger.date.desc()).limit(500)
    )
    tzedakah_raw = tz_result.scalars().all()
    tzedakah = []
    total_tz = 0.0
    for t in tzedakah_raw:
        amt = t.maaser_paid or t.income_amount or 0
        tzedakah.append({
            "amount": amt,
            "recipient": t.paid_to or "",
            "note": t.note or "",
            "date": t.date.isoformat() if t.date else "",
        })
        total_tz += amt

    return {
        "txs": txs, "income": income, "spend": spend, "balance": balance,
        "savings_rate": savings_rate, "health_score": health_score,
        "categories": cat_list, "budgets": budgets,
        "tzedakah": tzedakah, "total_tzedakah": total_tz,
    }


def build_router() -> APIRouter:
    router = APIRouter(prefix="/reports", tags=["reports"])

    @router.get("/monthly")
    async def monthly(request: Request, month: str = Query(None, description="YYYY-MM"),
                      user: dict = Depends(get_current_user)):
        if not month:
            month = datetime.now(timezone.utc).strftime("%Y-%m")
        try:
            sm = request.app.state.db
            async with sm() as session:
                data = await _gather(session, user["user_id"], month=month)
            return _build_pdf(user, data, kind=f"Monthly report · {month}", filename=f"financeai-{month}.pdf")
        except Exception as e:
            logger.exception("Monthly report generation failed for user %s: %s", user.get("user_id"), e)
            raise HTTPException(500, "Report generation failed. Please try again.")

    @router.get("/yearly")
    async def yearly(request: Request, year: int = Query(None),
                     user: dict = Depends(get_current_user)):
        if not year:
            year = datetime.now(timezone.utc).year
        try:
            sm = request.app.state.db
            async with sm() as session:
                data = await _gather(session, user["user_id"], year=year)
            return _build_pdf(user, data, kind=f"Yearly report · {year}", filename=f"financeai-{year}.pdf", yearly=True)
        except Exception as e:
            logger.exception("Yearly report generation failed for user %s: %s", user.get("user_id"), e)
            raise HTTPException(500, "Report generation failed. Please try again.")

    @router.get("/full")
    async def full(request: Request, user: dict = Depends(get_current_user)):
        try:
            sm = request.app.state.db
            async with sm() as session:
                data = await _gather(session, user["user_id"])
            return _build_pdf(user, data, kind="Full financial snapshot",
                              filename=f"financeai-snapshot-{datetime.now(timezone.utc).strftime('%Y%m%d')}.pdf",
                              full=True)
        except Exception as e:
            logger.exception("Full report generation failed for user %s: %s", user.get("user_id"), e)
            raise HTTPException(500, "Report generation failed. Please try again.")

    return router


def _build_pdf(user: dict, data: dict, kind: str, filename: str,
               yearly: bool = False, full: bool = False) -> StreamingResponse:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4,
                            leftMargin=15 * mm, rightMargin=15 * mm,
                            topMargin=22 * mm, bottomMargin=18 * mm)
    s = _styles()
    elems = []

    elems.append(Paragraph(kind, s["title"]))
    elems.append(Paragraph(f"Prepared for <b>{user.get('name') or user.get('email')}</b> · {datetime.now(timezone.utc).strftime('%d %B %Y')}", s["sub"]))

    elems.append(_kpi_table(s, [
        ("INCOME", f"£{data['income']:.2f}"),
        ("SPEND", f"£{data['spend']:.2f}"),
        ("NET", f"£{data['balance']:.2f}"),
        ("HEALTH SCORE", f"{data['health_score']}/100"),
    ]))

    elems.append(Paragraph("Top spending categories", s["h2"]))
    if data["categories"]:
        elems.append(_cat_table(s, data["categories"]))
    else:
        elems.append(Paragraph("No spending recorded for this period.", s["muted"]))

    elems.append(Paragraph("AI insights", s["h2"]))
    insights = [
        f"Savings rate is <b>{data['savings_rate']:.1f}%</b>. "
        + ("Excellent discipline." if data['savings_rate'] >= 20 else "Aim for 20% to build wealth steadily." if data['savings_rate'] >= 10 else "Tighten discretionary spend this month."),
        f"Top spending category is <b>{data['categories'][0]['name'].capitalize() if data['categories'] else '—'}</b>"
        + (f" at <b>£{data['categories'][0]['value']:.2f}</b>." if data['categories'] else "."),
        f"Total given to Tzedakah on file: <b>£{data['total_tzedakah']:.2f}</b>.",
        "Build an emergency fund of 3-6 months expenses before increasing investments.",
    ]
    for ins in insights:
        elems.append(Paragraph(f"→ {ins}", s["body"]))

    if data["budgets"]:
        elems.append(Paragraph("Budgets", s["h2"]))
        rows = [["Category", "Limit", "Spent", "Remaining"]]
        for b in data["budgets"]:
            rows.append([b["category"].capitalize(),
                         f"£{b['limit']:.2f}", f"£{b['spent']:.2f}",
                         f"£{(b['limit'] - b['spent']):.2f}"])
        bt = Table(rows, colWidths=[60 * mm, 30 * mm, 30 * mm, 30 * mm])
        bt.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), INK),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, 0), 8),
            ("FONTSIZE", (0, 1), (-1, -1), 9),
            ("ALIGN", (1, 1), (-1, -1), "RIGHT"),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, SOFT]),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ]))
        elems.append(bt)

    elems.append(PageBreak())
    elems.append(Paragraph("Transactions", s["h2"]))
    if data["txs"]:
        elems.append(_tx_table(s, data["txs"], limit=None if full else 80))
    else:
        elems.append(Paragraph("No transactions in this period.", s["muted"]))

    if full and data["tzedakah"]:
        elems.append(PageBreak())
        elems.append(Paragraph("Tzedakah ledger", s["h2"]))
        rows = [["Date", "Recipient", "Note", "Amount"]]
        for t in data["tzedakah"]:
            rows.append([(t.get("date") or "")[:10], t.get("recipient", ""),
                         (t.get("note") or "")[:40], f"£{t['amount']:.2f}"])
        tz = Table(rows, colWidths=[24 * mm, 50 * mm, 60 * mm, 30 * mm])
        tz.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), INK),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, 0), 8),
            ("FONTSIZE", (0, 1), (-1, -1), 9),
            ("ALIGN", (-1, 1), (-1, -1), "RIGHT"),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, SOFT]),
        ]))
        elems.append(tz)

    email = user.get("email", "")
    def on_page(c, d): _header_footer(c, d, email, kind)
    doc.build(elems, onFirstPage=on_page, onLaterPages=on_page)
    buf.seek(0)
    return StreamingResponse(buf, media_type="application/pdf",
                              headers={"Content-Disposition": f'attachment; filename="{filename}"'})
